# For more information: https://laravel.com/docs/sail
version: '3'
services:
  laravel:
    build: .
    networks:
      - local
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/var/www/html
      - vendordata:/var/www/html/vendor:rw,delegated
  mariadb:
    image: mariadb:11.1.2
    restart: always
    networks:
      - local
    ports:
      - 3306:3306
    volumes:
      - mydb:/var/lib/mysql:rw,delegated
    environment:
      MARIADB_ROOT_PASSWORD: onboarding23
      MARIADB_DATABASE: onboarding
      MARIADB_USER: laravel
      MARIADB_PASSWORD: onboarding23
      MARIADB_MYSQL_LOCALHOST_PASSWORD: onboarding
  redis:
    ports:
      - 6379:6379
    networks:
      - local
    image: redis:4.0.14-alpine
volumes:
  mydb:
    driver: local
  vendordata:
    driver: local
networks:
  local:
